/*

    EndPwn3 System
    
    Copyright 2018 EndPwn Project
    
    Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
    
    The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
    
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

    DO NOT EDIT THIS FILE! Your bootstrap may overwrite changes to it, and you will lose your work!
    EndPwn3 users: You can prevent this by creating a file in the same directory named DONTUPDATE
    
    https://github.com/endpwn/

*/

const util = mrequire('xyz.dr1ft.epapi.core');

function print(str) {
    console.log(`%c[EndPwn3]%c ` + str, 'font-weight:bold;color:#0cc', '');
}

module.exports = function () {
    // fuck sentry
    print('fucking sentry...');
    var sentry = wc.findCache('_originalConsoleMethods')[0].exports;
    window.console = Object.assign(window.console, sentry._originalConsoleMethods); // console
    sentry._wrappedBuiltIns.forEach(x => x[0][x[1]] = x[2]); // other stuff
    sentry._breadcrumbEventHandler = () => () => { }; // break most event logging
    sentry.captureBreadcrumb = () => { }; // disable breadcrumb logging
}